### ISSUE TITLE
Profiles to test the positioning procedure in the Arctic

### ISSUE THREAD

**Issue by imab4bsh** [euroargodev/Coriolis-under-ice-positioning#1]
In our work for deliverable [D2.7](https://www.euro-argo.eu/content/download/162917/file/D2.7_MarginalSeasDMQC_V2.1_under_EC_review.pdf) we used the [terrain-following python code](https://github.com/euroargodev/terrain-following) to calculate the under-ice positions of several floats. In Table 4.1 (page 54, copied below) you can find the wmo number of all those floats and the results we got from the interpolation procedure. We could use the floats with bad results and the ones that resulted in errors to see if your improvemed code has better results.

![image](https://user-images.githubusercontent.com/58477386/204580634-002d5c07-6303-48d5-ad97-0875ddcb7096.png)

**Comment by catsch** [comment]
see https://github.com/euroargodev/Coriolis-under-ice-positioning/issues/2
