### ISSUE TITLE
No backwards path for 7900549 cycles 010-048

### ISSUE THREAD

**Issue by imab4bsh** [euroargodev/Coriolis-under-ice-positioning#2]
Using your script to calculate the trajectory of float number 7900549 I face an error because it is not possible to find a backwards path for the segment made of cycles 010 to 048.. I changed some configurations and the error persists. It is possible to use the forward path and allow the script to calculate the rest of the trajectory?
```

Error using validateHandleToPrint
No figure to print.
Error in validate (line 17)
pj = validateHandleToPrint(pj);
Error in print (line 67)
pj = validate( pj );
Error in estimate_profile_locations>process_set_of_cycles (line 657)
            print('-dpng', [a_outputDir '/' plotFileName '.png']);
Error in estimate_profile_locations>process_float_data (line 335)
   a_floatData = process_set_of_cycles(a_floatNum, a_floatData, idS, idStart, idStop, a_outputDir, a_gebcoFilePathName);
Error in estimate_profile_locations (line 164)
   process_float_data(floatNum, floatData, [DIR_OUTPUT_FILES '/' floatNumStr '/'], GEBCO_FILE); 
```

**Comment by catsch** [comment]
11 floats trajectories have been performed there with no issues  
ftp://ftp.ifremer.fr/ifremer/sismer/coriolis/jpr/ESTIMATE_PROFILE_POSITION_20231213/
could you check that it is Ok, for you ?
these are only indications that need to be checked by a DM operator

**Comment by imab4bsh** [comment]
@catsch thanks for calculating the trajectories for me. I will check them.
